config/routes.rb
Funpages::Application.routes.draw do

  devise_for :users

  devise_scope :user do
  	get 'users/sign_out' => 'devise/sessions#destroy'	
  end

	root :to => 'home#index'

	controller :home do
		match 'home', :action => 'index', :as => 'home'
		match 'second', :action => 'second', :as => 'second'
	end

	controller :profile do
		match 'profile', :action => 'index', :as => 'profile'
		match 'profile/edit', :action => 'edit', :as => 'profile_edit'
		match 'profile/update', :action => 'update', :as => 'profile_update'
	end

	resources :posts
	
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :message, :name

  default_scope :order => 'created_at DESC'

  belongs_to :user
  
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  attr_accessible :about_me, :dob, :gender, :hobbies, :native_place, :present_place
	
	def self.genders
		[ ['Male', 'm'], ['Female', 'f'] ]
  end

end

app/models/user.rb
class User < ActiveRecord::Base

	after_create :set_default_associations

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable



  # validations
  validates :first_name, :last_name, :presence => true
  # validates_presence_of :first_name, :last_name


  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name

  has_many :posts, :dependent => :destroy
  has_one :profile, :dependent => :destroy

  def set_default_associations
  	self.create_profile
  end

  def full_name
		self.first_name + ' ' + self.last_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :authenticate_user!

	layout 'two_column'

	def index
		@hello = 'Hello world!'
		@fruits = ['apple', 'banana', 'custard', 'water melon']
	end

	def second
		render :layout => 'application'
	end

	def posts
		@posts = Post.all
	end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@posts = Post.all		
	end

	def show
		@post = Post.find params[:id]
	end

	def new
		@post = Post.new
	end

	def create
		if params[:post]
			current_user.posts.create params[:post]
		end
		redirect_to posts_path
	end

	def edit
		@post = Post.find params[:id]
	end

	def update
		if params[:post]
			@post = Post.find params[:id]
			@post.update_attributes params[:post]
		end
		redirect_to posts_path
	end


	def destroy
		if params[:id]
			@post = Post.delete params[:id]
		end
		redirect_to posts_path
	end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
	
	def vars
		@user = current_user
		@profile = @user.profile
	end
	
	def index
		vars
	end

	def edit
		vars
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.slim
div
	= @hello
	ul
		- @fruits.each do |f|
			li= f

app/views/home/posts.html.slim
h3 Posts

- @posts.each do |p|
	= p.name
	br
	= p.message
	hr

app/views/home/second.html.slim
div This is second page.

app/views/layouts/application.html.slim
doctype html
html
	head
		title Funpages
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	body
		header
			.container
				= render :partial => 'shared/navigation'

		= render 'shared/flash_messages'
		
		.container.mt50.content
			.container_pad
				= yield

app/views/layouts/two_column.html.slim
doctype html
html
	head
		title Funpages
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
	body
		.container.mt50.content
			.left_panel
				.side_links
					= render :partial => 'shared/navigation'
				.pam
			.right_panel
				.pam
					= yield
			.clearfix

app/views/posts/_form.html.slim
= semantic_form_for @post do |f|
	= f.input :message, :input_html => { :rows => 5 }
	.fr= f.submit 'Post'
	.clearfix

app/views/posts/edit.html.slim
h3 Edit post

= render :partial => 'form'

app/views/posts/index.html.slim
h3 Posts

.fr= link_to 'New Post', new_post_path
.clearfix

- @posts.each do |p|
	= p.user.full_name
	br
	.fl= p.message
	.fr
		= link_to 'show', post_path(p.id)
		= " | "
		= link_to 'Edit', edit_post_path(p.id)
		= " | "
		= link_to 'Delete', post_path(p.id), :method => 'Delete', :confirm => 'You might me nuts?? Seriously??'
	.clearfix

	hr

app/views/posts/new.html.slim
h3 New post

= render :partial => 'form'

app/views/posts/show.html.slim
- p = @post

.fr= link_to 'Back to Posts', posts_path
.clearfix

h3= p.message

= p.name
br
= p.message
hr

app/views/shared/_flash_messages.html.slim
- if notice
	p.notice= notice
- if alert
	p.alert= alert

app/views/shared/_navigation.html.slim
- if !user_signed_in?
	= link_to 'Sign In', new_user_session_path
	= link_to 'Sign Up', new_user_registration_path
- if user_signed_in?
	= link_to 'Home', home_path
	= link_to 'Second', second_path
	= link_to 'Posts', posts_path
	= link_to 'Profile', profile_path
	= link_to 'Sign out', destroy_user_session_path

.clearfix